package sali.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import sali.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.02 14:35:49 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HarjoitusTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi66 */
  @Test
  public void testRekisteroi66() {    // Harjoitus: 66
    Harjoitus treeni1 = new Harjoitus(); 
    assertEquals("From: Harjoitus line: 68", 0, treeni1.getHarjoitusID()); 
    treeni1.rekisteroi(); 
    Harjoitus treeni2 = new Harjoitus(); 
    treeni2.rekisteroi(); 
    int n1 = treeni1.getHarjoitusID(); 
    int n2 = treeni2.getHarjoitusID(); 
    assertEquals("From: Harjoitus line: 74", n2-1, n1); 
  } // Generated by ComTest END
}