package sali.test;
// Generated by ComTest BEGIN
import sali.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.02 15:28:58 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HarjoituksetTest {



  // Generated by ComTest BEGIN
  /** testIterator70 */
  @Test
  public void testIterator70() {    // Harjoitukset: 70
    Harjoitukset treenit = new Harjoitukset(); 
    Harjoitus reeni1 = new Harjoitus(); treenit.lisaa(reeni1); 
    Harjoitus reeni2 = new Harjoitus(); treenit.lisaa(reeni2); 
    Harjoitus reeni3 = new Harjoitus(); treenit.lisaa(reeni3); 
    Harjoitus reeni4 = new Harjoitus(); treenit.lisaa(reeni4); 
    Harjoitus reeni5 = new Harjoitus(); treenit.lisaa(reeni5); 
    Iterator<Harjoitus> i2=treenit.iterator(); 
    assertEquals("From: Harjoitukset line: 82", reeni1, i2.next()); 
    assertEquals("From: Harjoitukset line: 83", reeni2, i2.next()); 
    assertEquals("From: Harjoitukset line: 84", reeni3, i2.next()); 
    assertEquals("From: Harjoitukset line: 85", reeni4, i2.next()); 
    assertEquals("From: Harjoitukset line: 86", reeni5, i2.next()); 
    try {
    assertEquals("From: Harjoitukset line: 87", reeni3, i2.next()); 
    fail("Harjoitukset: 87 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaHarjoitukset100 */
  @Test
  public void testAnnaHarjoitukset100() {    // Harjoitukset: 100
    Harjoitukset treenit = new Harjoitukset(); 
    Harjoitus reeni1 = new Harjoitus(); treenit.lisaa(reeni1); 
    Harjoitus reeni2 = new Harjoitus(); treenit.lisaa(reeni2); 
    Harjoitus reeni3 = new Harjoitus(); treenit.lisaa(reeni3); 
    Harjoitus reeni4 = new Harjoitus(); treenit.lisaa(reeni4); 
    Harjoitus reeni5 = new Harjoitus(); treenit.lisaa(reeni5); 
    List<Harjoitus> loytyneet; 
    loytyneet = treenit.annaHarjoitukset(); 
    assertEquals("From: Harjoitukset line: 112", 5, loytyneet.size()); 
    assertEquals("From: Harjoitukset line: 113", true, loytyneet.get(0) == reeni1); 
    assertEquals("From: Harjoitukset line: 114", true, loytyneet.get(3) == reeni4); 
  } // Generated by ComTest END
}