package sali.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import sali.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.26 21:55:04 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class LiikeTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi45 */
  @Test
  public void testRekisteroi45() {    // Liike: 45
    Liike kyykky = new Liike(); 
    assertEquals("From: Liike line: 47", 0, kyykky.getLiikeID()); 
    kyykky.rekisteroi(); 
    Liike penkki = new Liike(); 
    penkki.rekisteroi(); 
    int n1 = kyykky.getLiikeID(); 
    int n2 = penkki.getLiikeID(); 
    assertEquals("From: Liike line: 53", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLiikeNimi76 */
  @Test
  public void testGetLiikeNimi76() {    // Liike: 76
    Liike dippi = new Liike(); 
    dippi.setLiikeNimi("dippi"); 
    assertEquals("From: Liike line: 79", "dippi", dippi.getLiikeNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetLiikeNimi91 */
  @Test
  public void testSetLiikeNimi91() {    // Liike: 91
    Liike pystypunnerrus = new Liike(); 
    pystypunnerrus.setLiikeNimi("pystypunnerrus"); 
    assertEquals("From: Liike line: 94", "pystypunnerrus", pystypunnerrus.getLiikeNimi()); 
  } // Generated by ComTest END
}