package sali.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import sali.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.26 22:06:59 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class LiikeTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi44 */
  @Test
  public void testRekisteroi44() {    // Liike: 44
    Liike kyykky = new Liike(); 
    assertEquals("From: Liike line: 46", 0, kyykky.getLiikeID()); 
    kyykky.rekisteroi(); 
    Liike penkki = new Liike(); 
    penkki.rekisteroi(); 
    int n1 = kyykky.getLiikeID(); 
    int n2 = penkki.getLiikeID(); 
    assertEquals("From: Liike line: 52", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLiikeNimi75 */
  @Test
  public void testGetLiikeNimi75() {    // Liike: 75
    Liike dippi = new Liike(); 
    dippi.setLiikeNimi("dippi"); 
    assertEquals("From: Liike line: 78", "dippi", dippi.getLiikeNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetLiikeNimi90 */
  @Test
  public void testSetLiikeNimi90() {    // Liike: 90
    Liike pystypunnerrus = new Liike(); 
    pystypunnerrus.setLiikeNimi("pystypunnerrus"); 
    assertEquals("From: Liike line: 93", "pystypunnerrus", pystypunnerrus.getLiikeNimi()); 
  } // Generated by ComTest END
}