package sali.test;
// Generated by ComTest BEGIN
import sali.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.27 13:29:55 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class LiikkeetTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa56 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa56() throws SailoException {    // Liikkeet: 56
    Liikkeet liikkeet = new Liikkeet(); 
    Liike kyykky = new Liike(), penkki = new Liike(), maastaveto = new Liike(),
    dippi = new Liike(), pystypunnerrus = new Liike(), alatalja = new Liike(); 
    assertEquals("From: Liikkeet line: 61", 0, liikkeet.getLkm()); 
    liikkeet.lisaa(kyykky); assertEquals("From: Liikkeet line: 62", 1, liikkeet.getLkm()); 
    liikkeet.lisaa(penkki); assertEquals("From: Liikkeet line: 63", 2, liikkeet.getLkm()); 
    liikkeet.lisaa(maastaveto); assertEquals("From: Liikkeet line: 64", 3, liikkeet.getLkm()); 
    try {
    liikkeet.lisaa(maastaveto); 
    fail("Liikkeet: 65 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    assertEquals("From: Liikkeet line: 66", kyykky, liikkeet.anna(0)); 
    assertEquals("From: Liikkeet line: 67", penkki, liikkeet.anna(1)); 
    assertEquals("From: Liikkeet line: 68", maastaveto, liikkeet.anna(2)); 
    assertEquals("From: Liikkeet line: 69", false, liikkeet.anna(1) == kyykky); 
    assertEquals("From: Liikkeet line: 70", true, liikkeet.anna(1) == penkki); 
    try {
    assertEquals("From: Liikkeet line: 71", kyykky, liikkeet.anna(3)); 
    fail("Liikkeet: 71 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    liikkeet.lisaa(dippi); assertEquals("From: Liikkeet line: 72", 4, liikkeet.getLkm()); 
    liikkeet.lisaa(pystypunnerrus); assertEquals("From: Liikkeet line: 73", 5, liikkeet.getLkm()); 
    try {
    liikkeet.lisaa(alatalja); 
    fail("Liikkeet: 74 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista91 
   * @throws SailoException when error
   */
  @Test
  public void testPoista91() throws SailoException {    // Liikkeet: 91
    Liikkeet liikkeet = new Liikkeet(); 
    Liike kyykky = new Liike(), penkki = new Liike(), maastaveto = new Liike(); 
    kyykky.rekisteroi(); penkki.rekisteroi(); maastaveto.rekisteroi(); 
    int id1 = kyykky.getLiikeID(); 
    liikkeet.lisaa(kyykky); liikkeet.lisaa(penkki); liikkeet.lisaa(maastaveto); 
    assertEquals("From: Liikkeet line: 98", 1, liikkeet.poista(id1+1)); 
    assertEquals("From: Liikkeet line: 99", null, liikkeet.annaId(id1+1)); assertEquals("From: Liikkeet line: 99", 2, liikkeet.getLkm()); 
    assertEquals("From: Liikkeet line: 100", 1, liikkeet.poista(id1)); assertEquals("From: Liikkeet line: 100", 1, liikkeet.getLkm()); 
    assertEquals("From: Liikkeet line: 101", 0, liikkeet.poista(id1+3)); assertEquals("From: Liikkeet line: 101", 1, liikkeet.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnnaId134 
   * @throws SailoException when error
   */
  @Test
  public void testAnnaId134() throws SailoException {    // Liikkeet: 134
    Liikkeet liikkeet = new Liikkeet(); 
    Liike kyykky = new Liike(), penkki = new Liike(), maastaveto = new Liike(); 
    kyykky.rekisteroi(); penkki.rekisteroi(); maastaveto.rekisteroi(); 
    int id1 = kyykky.getLiikeID(); 
    liikkeet.lisaa(kyykky); liikkeet.lisaa(penkki); liikkeet.lisaa(maastaveto); 
    assertEquals("From: Liikkeet line: 141", true, liikkeet.annaId(id1  ) == kyykky); 
    assertEquals("From: Liikkeet line: 142", true, liikkeet.annaId(id1+1) == penkki); 
    assertEquals("From: Liikkeet line: 143", true, liikkeet.annaId(id1+2) == maastaveto); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLiikkeetIterator157 
   * @throws SailoException when error
   */
  @Test
  public void testLiikkeetIterator157() throws SailoException {    // Liikkeet: 157
    Liikkeet liikkeet = new Liikkeet(); 
    Liike kyykky = new Liike(), penkki = new Liike(), maastaveto = new Liike(); 
    kyykky.rekisteroi(); penkki.rekisteroi(); maastaveto.rekisteroi(); 
    liikkeet.lisaa(kyykky); liikkeet.lisaa(penkki); liikkeet.lisaa(maastaveto); 
    StringBuffer ids = new StringBuffer(30); 
    for (Liike liike:liikkeet) // Kokeillaan for-silmukan toimintaa
    ids.append(" "+liike.getLiikeID()); 
    String tulos = " " + kyykky.getLiikeID() + " " + penkki.getLiikeID() + " " + maastaveto.getLiikeID(); 
    assertEquals("From: Liikkeet line: 174", tulos, ids.toString()); 
    ids = new StringBuffer(30); 
    for (Iterator<Liike>  i=liikkeet.iterator(); i.hasNext(); ) { // ja iteraattorin toimintaa
    Liike liike = i.next(); 
    ids.append(" "+liike.getLiikeID()); 
    }
    assertEquals("From: Liikkeet line: 182", tulos, ids.toString()); 
    Iterator<Liike>  i=liikkeet.iterator(); 
    assertEquals("From: Liikkeet line: 185", true, i.next() == kyykky); 
    assertEquals("From: Liikkeet line: 186", true, i.next() == penkki); 
    assertEquals("From: Liikkeet line: 187", true, i.next() == maastaveto); 
    try {
    i.next(); 
    fail("Liikkeet: 189 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsiId250 
   * @throws SailoException when error
   */
  @Test
  public void testEtsiId250() throws SailoException {    // Liikkeet: 250
    Liikkeet liikkeet = new Liikkeet(); 
    Liike kyykky = new Liike(), penkki = new Liike(), maastaveto = new Liike(); 
    kyykky.rekisteroi(); penkki.rekisteroi(); maastaveto.rekisteroi(); 
    int id1 = kyykky.getLiikeID(); 
    liikkeet.lisaa(kyykky); liikkeet.lisaa(penkki); liikkeet.lisaa(maastaveto); 
    assertEquals("From: Liikkeet line: 257", 1, liikkeet.etsiId(id1+1)); 
    assertEquals("From: Liikkeet line: 258", 2, liikkeet.etsiId(id1+2)); 
  } // Generated by ComTest END
}