package sali.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import sali.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.29 16:47:48 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class SailoExceptionTest {
}