package sali.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import sali.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.27 13:36:52 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class SaliTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa40 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa40() throws SailoException {    // Sali: 40
    Sali sali = new Sali(); 
    Suoritus kyykkysarja1 = new Suoritus(), kyykkysarja2 = new Suoritus(); 
    kyykkysarja1.rekisteroi(); kyykkysarja2.rekisteroi(); 
    assertEquals("From: Sali line: 45", 0, sali.getSuorituksia()); 
    sali.lisaa(kyykkysarja1); assertEquals("From: Sali line: 46", 1, sali.getSuorituksia()); 
    sali.lisaa(kyykkysarja2); assertEquals("From: Sali line: 47", 2, sali.getSuorituksia()); 
    sali.lisaa(kyykkysarja1); assertEquals("From: Sali line: 48", 3, sali.getSuorituksia()); 
    assertEquals("From: Sali line: 49", 3, sali.getSuorituksia()); 
    assertEquals("From: Sali line: 50", kyykkysarja1, sali.annaSuoritus(0)); 
    assertEquals("From: Sali line: 51", kyykkysarja2, sali.annaSuoritus(1)); 
    assertEquals("From: Sali line: 52", kyykkysarja1, sali.annaSuoritus(2)); 
    try {
    assertEquals("From: Sali line: 53", kyykkysarja1, sali.annaSuoritus(3)); 
    fail("Sali: 53 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    sali.lisaa(kyykkysarja1); assertEquals("From: Sali line: 54", 4, sali.getSuorituksia()); 
    sali.lisaa(kyykkysarja1); assertEquals("From: Sali line: 55", 5, sali.getSuorituksia()); 
    sali.lisaa(kyykkysarja1); assertEquals("From: Sali line: 56", 6, sali.getSuorituksia()); 
    sali.lisaa(kyykkysarja1); assertEquals("From: Sali line: 57", 7, sali.getSuorituksia()); 
    sali.lisaa(kyykkysarja1); assertEquals("From: Sali line: 58", 8, sali.getSuorituksia()); 
    try {
    sali.lisaa(kyykkysarja1); 
    fail("Sali: 59 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}