package sali.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import sali.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.24 21:59:12 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class SuoritusTest {



  // Generated by ComTest BEGIN
  /** testGetLiikeID51 */
  @Test
  public void testGetLiikeID51() {    // Suoritus: 51
    Suoritus kyykkysarja = new Suoritus(); 
    kyykkysarja.taytaKyykkyTiedoilla(); 
    assertEquals("From: Suoritus line: 54", 1, kyykkysarja.getLiikeID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi102 */
  @Test
  public void testRekisteroi102() {    // Suoritus: 102
    Suoritus kyykkysarja1 = new Suoritus(); 
    assertEquals("From: Suoritus line: 104", 0, kyykkysarja1.getTunnusNro()); 
    kyykkysarja1.rekisteroi(); 
    Suoritus kyykkysarja2 = new Suoritus(); 
    kyykkysarja2.rekisteroi(); 
    int n1 = kyykkysarja1.getTunnusNro(); 
    int n2 = kyykkysarja2.getTunnusNro(); 
    assertEquals("From: Suoritus line: 110", n2-1, n1); 
  } // Generated by ComTest END
}