package sali.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import sali.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.02 15:32:05 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class SuorituksetTest {



  // Generated by ComTest BEGIN
  /** testLisaa50 */
  @Test
  public void testLisaa50() {    // Suoritukset: 50
    Suoritukset suoritukset = new Suoritukset(); 
    Suoritus kyykkysarja1 = new Suoritus(), kyykkysarja2 = new Suoritus(); 
    assertEquals("From: Suoritukset line: 53", 0, suoritukset.getLkm()); 
    suoritukset.lisaa(kyykkysarja1); assertEquals("From: Suoritukset line: 54", 1, suoritukset.getLkm()); 
    suoritukset.lisaa(kyykkysarja2); assertEquals("From: Suoritukset line: 55", 2, suoritukset.getLkm()); 
    suoritukset.lisaa(kyykkysarja1); assertEquals("From: Suoritukset line: 56", 3, suoritukset.getLkm()); 
    assertEquals("From: Suoritukset line: 57", kyykkysarja1, suoritukset.anna(0)); 
    assertEquals("From: Suoritukset line: 58", kyykkysarja2, suoritukset.anna(1)); 
    assertEquals("From: Suoritukset line: 59", kyykkysarja1, suoritukset.anna(2)); 
    assertEquals("From: Suoritukset line: 60", false, suoritukset.anna(1) == kyykkysarja1); 
    assertEquals("From: Suoritukset line: 61", true, suoritukset.anna(1) == kyykkysarja2); 
    try {
    assertEquals("From: Suoritukset line: 62", kyykkysarja1, suoritukset.anna(3)); 
    fail("Suoritukset: 62 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    suoritukset.lisaa(kyykkysarja1); assertEquals("From: Suoritukset line: 63", 4, suoritukset.getLkm()); 
    suoritukset.lisaa(kyykkysarja1); assertEquals("From: Suoritukset line: 64", 5, suoritukset.getLkm()); 
    suoritukset.lisaa(kyykkysarja1); assertEquals("From: Suoritukset line: 65", 6, suoritukset.getLkm()); 
    suoritukset.lisaa(kyykkysarja1); assertEquals("From: Suoritukset line: 66", 7, suoritukset.getLkm()); 
    suoritukset.lisaa(kyykkysarja1); assertEquals("From: Suoritukset line: 67", 8, suoritukset.getLkm()); 
    suoritukset.lisaa(kyykkysarja1); assertEquals("From: Suoritukset line: 68", 9, suoritukset.getLkm());  // Tässä luodaan kasvatettu taulukko, jotta kaikki mahtuu
  } // Generated by ComTest END
}