package sali.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import sali.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.27 15:46:26 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class SuoritusTest {



  // Generated by ComTest BEGIN
  /** testGetHarjoitusID52 */
  @Test
  public void testGetHarjoitusID52() {    // Suoritus: 52
    Suoritus kyykkysarja = new Suoritus(); 
    assertEquals("From: Suoritus line: 54", 0, kyykkysarja.getHarjoitusID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLiikeID65 */
  @Test
  public void testGetLiikeID65() {    // Suoritus: 65
    Suoritus kyykkysarja = new Suoritus(); 
    kyykkysarja.taytaKyykkyTiedoilla(); 
    assertEquals("From: Suoritus line: 68", 1, kyykkysarja.getLiikeID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetSarjat79 */
  @Test
  public void testGetSarjat79() {    // Suoritus: 79
    Suoritus kyykkysarja = new Suoritus(); 
    kyykkysarja.taytaKyykkyTiedoilla(); 
    assertEquals("From: Suoritus line: 82", 3, kyykkysarja.getSarjat()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetToistot93 */
  @Test
  public void testGetToistot93() {    // Suoritus: 93
    Suoritus kyykkysarja = new Suoritus(); 
    kyykkysarja.taytaKyykkyTiedoilla(); 
    assertEquals("From: Suoritus line: 96", 5, kyykkysarja.getToistot()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetPainot107 */
  @Test
  public void testGetPainot107() {    // Suoritus: 107
    Suoritus kyykkysarja = new Suoritus(); 
    kyykkysarja.taytaKyykkyTiedoilla(); 
    assertEquals("From: Suoritus line: 110", 160, kyykkysarja.getPainot(), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetRasitus121 */
  @Test
  public void testGetRasitus121() {    // Suoritus: 121
    Suoritus kyykkysarja = new Suoritus(); 
    kyykkysarja.taytaKyykkyTiedoilla(); 
    assertEquals("From: Suoritus line: 124", 8, kyykkysarja.getRasitus(), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKommentit135 */
  @Test
  public void testGetKommentit135() {    // Suoritus: 135
    Suoritus kyykkysarja = new Suoritus(); 
    kyykkysarja.taytaKyykkyTiedoilla(); 
    assertEquals("From: Suoritus line: 138", "Selkä kipeä", kyykkysarja.getKommentit()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi186 */
  @Test
  public void testRekisteroi186() {    // Suoritus: 186
    Suoritus kyykkysarja1 = new Suoritus(); 
    assertEquals("From: Suoritus line: 188", 0, kyykkysarja1.getTunnusNro()); 
    kyykkysarja1.rekisteroi(); 
    Suoritus kyykkysarja2 = new Suoritus(); 
    kyykkysarja2.rekisteroi(); 
    int n1 = kyykkysarja1.getTunnusNro(); 
    int n2 = kyykkysarja2.getTunnusNro(); 
    assertEquals("From: Suoritus line: 194", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnna218 */
  @Test
  public void testAnna218() {    // Suoritus: 218
    Suoritus kyykkysarja = new Suoritus(); 
    kyykkysarja.taytaKyykkyTiedoilla(); 
    assertEquals("From: Suoritus line: 221", "Selkä kipeä", kyykkysarja.anna(5)); 
  } // Generated by ComTest END
}