package fxSali.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxSali.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.10 17:30:18 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class SaliGUIControllerTest {
}